spring:
  application:
    name: spring-template
  profiles:
    active:
      - workflow

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/w2-api?allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    hikari:
      minimum-idle: 5
      idle-timeout: 30000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: w2HikariCP
      max-lifetime: 1800000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      validation-timeout: 3000
      health-check-properties: {}
  jpa:
    database: mysql
    generate-ddl: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        user_sql_comments: true
  liquibase:
    enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: Cr4gs54ZXKJoVFYBV5J
    database: 0
    timeout: 6000
    connectTimeout: 10000
    clientName: w2-server

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 19999