spring:
  application:
    name: spring-template

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/w2-api
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: w2HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    generate-ddl: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        user_sql_comments: true

  redis:
    host: 124.70.32.167
    port: 19528
    password: Cr4gs54ZXKJoVFYBV5J
    database: 0


server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
