w2:
  flowable:
    processor:
      enabled: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/w2_flowable?autoReconnect=true&nullCatalogMeansCurrent=true
      username: root
      password: 123456789
