w2:
  flowable:
    processor:
      enabled: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.70.32.167:33306/study_flowable?autoReconnect=true&nullCatalogMeansCurrent=true
      username: root
      password: 123456789
